BATCH_SIZE = 128
LEARNING_RATE = 0.1 * (BATCH_SIZE/512)
SAVE_FREQ = 1
TEST_FREQ = 1
TOTAL_EPOCH = 30
FINAL_EMBEDDING_SIZE = 128
QUICK_TEST = False

RESUME = '' #'./results/CASIA_20251224_233404/001.ckpt'
SAVE_DIR = './results'
MODEL_PRE = f'CASIA_'

CASIA_DATA_DIR = './Datasets/CASIA'
LFW_DATA_DIR = './Datasets/LFW'
AGEDB_DATA_DIR = './Datasets/AgeDB'

CASIA_ALIGNED_DATA_DIR = './Datasets/CASIA_ALIGNED'
LFW_ALIGNED_DATA_DIR = './Datasets/LFW_ALIGNED'
AGEDB_ALIGNED_DATA_DIR = './Datasets/AgeDB_ALIGNED'